FROM python:3.11-alpine

WORKDIR /app

COPY ragasenv.txt .

RUN pip install --no-cache-dir -r ragasenv.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "ragBalance.py:app"]
